// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/core-data/core-data.proto

package go_micro_service_coredata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CoreData service

func NewCoreDataEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CoreData service

type CoreDataService interface {
	SendRawData(ctx context.Context, in *SendDataRequest, opts ...client.CallOption) (*SendDataReply, error)
}

type coreDataService struct {
	c    client.Client
	name string
}

func NewCoreDataService(name string, c client.Client) CoreDataService {
	return &coreDataService{
		c:    c,
		name: name,
	}
}

func (c *coreDataService) SendRawData(ctx context.Context, in *SendDataRequest, opts ...client.CallOption) (*SendDataReply, error) {
	req := c.c.NewRequest(c.name, "CoreData.SendRawData", in)
	out := new(SendDataReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoreData service

type CoreDataHandler interface {
	SendRawData(context.Context, *SendDataRequest, *SendDataReply) error
}

func RegisterCoreDataHandler(s server.Server, hdlr CoreDataHandler, opts ...server.HandlerOption) error {
	type coreData interface {
		SendRawData(ctx context.Context, in *SendDataRequest, out *SendDataReply) error
	}
	type CoreData struct {
		coreData
	}
	h := &coreDataHandler{hdlr}
	return s.Handle(s.NewHandler(&CoreData{h}, opts...))
}

type coreDataHandler struct {
	CoreDataHandler
}

func (h *coreDataHandler) SendRawData(ctx context.Context, in *SendDataRequest, out *SendDataReply) error {
	return h.CoreDataHandler.SendRawData(ctx, in, out)
}
